services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        image: laravel_app
        container_name: laravel_app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
            LARAVEL_SAIL: 1
            XDEBUG_MODE: debug
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        networks:
            - laravel

    webserver:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - app
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            MYSQL_USER: root
            MYSQL_INIT_COMMAND: "--skip-host-cache=0"
        volumes:
            - mysql_data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        networks:
            - laravel

    mailpit:
        build:
            context: .
            dockerfile: docker/mailpit/Dockerfile
        container_name: mailpit
        ports:
            - "1025:1025"
            - "8025:8025"
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    mysql_data:
        driver: local
